import {
  mobile,
  backend,
  game,
  web,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  mongodb,
  git,
  figma,
  docker,
  cplusplus,
  csharp,
  sqlserver,
  swiftui,
  swift,
  unity,
  oraclelivesql,
  java,
  libgdx,
  silma,
  fugas,
  itesm,
  equilibrium,
  carrent,
  jobit,
  tripguide,
  threejs,
  inventory,
  compiler,
  simulator
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "Web Developer",
    icon: web,
  },
  {
    title: "Mobile Developer",
    icon: mobile,
  },
  {
    title: "Backend Developer",
    icon: backend,
  },
  {
    title: "Game Developer",
    icon: game,
  },
];

const technologies = [
  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Java",
    icon: java,
  },
  {
    name: "C++",
    icon: cplusplus,
  },
  {
    name: "C#",
    icon: csharp,
  },
  {
    name: "Swift UI",
    icon: swiftui,
  },
  {
    name: "Unity",
    icon: unity,
  }
];

const experiences = [
  {
    title: "UI Developer",
    company_name: "Equilibrium",
    icon: equilibrium,
    iconBg: "#E6DEDD",
    date: "February 2021 - June 2021",
    points: [
      "Developing a physics simulator app using SwiftUI",
      "Collaborating with other college students to deliver a product that high school students can use to learn.",
      "Implementing an intuitive design and ensuring cross-device compatibility.",
      "Participating in code reviews and providing constructive feedback to other college students.",
    ],
  },
  {
    title: "Compiler/VM Developer",
    company_name: "Obiecti - Tecnológico de Monterrey",
    icon: itesm,
    iconBg: "#383E56",
    date: "February 2022 - June 2022",
    points: [
      "Developing a new compiler and a virtual machine for a new programming language.",
      "Collaborating with other college student to design a new programming language in one semester.",
      "Implementing regular expressions, syntaxis diagrams, context-free grammar and other concepts related.",
      "Implementing a virtual machine so it can read and make operations following the instructions .obj file generated of a compiler.",
    ],
  }, 
  {
    title: "Android Auto Developer",
    company_name: "FuGas",
    icon: fugas,
    iconBg: "#E6DEDD",
    date: "September 2022",
    points: [
      "Winner of Blue Yonder's Challenge in Hack Mty 2022.",
      "Developing a car app using Android Auto, React.js and other related technologies.",
      "Collaborating with other college students to self-learn and solve a challenge under 24 hours.",
      "Implementing an interface easy to use so people can use it in a car without risking themselves.",
    ],
  }, 
  {
    title: "Backend Developer",
    company_name: "Silma",
    icon: silma,
    iconBg: "#383E56",
    date: "February 2023 - June 2023",
    points: [
      "Developing an inventory application for books and purchase items using React.js and other related technologies.",
      "Collaborating with other college students to self-learn front-end and back-end.",
      "Implementing a clean design and a robust structure that can be improved later on in the future.",
      "Participating in code reviews and providing feedback to other college students using SCRUM methodology with the help of a teacher.",
    ],
  }
];

const testimonials = [
  {
    testimonial:
      "Excellent in their approaches, a very careful and useful work that will be of great help to me in the editorial.",
    name: "Aurora Carranza",
    designation: "Author",
    company: "Silma",
    image: "https://i1.wp.com/www.silmaed.com/wp-content/uploads/2016/02/foto-de-aurora.jpg?resize=200%2C178",
  }
];

const projects = [
  {
    name: "Silma Inventory",
    description:
      "Inventory system for an independent editorial making easy manage books and purchase items as also product assortments.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "postgresql",
        color: "green-text-gradient",
      },
      {
        name: "serverless",
        color: "pink-text-gradient",
      },
    ],
    image: inventory,
    source_code_link: "https://github.com/gpaez-ol/silma",
  },
  {
    name: "Obiecti",
    description:
      "A compiler for a new programming language and virtual machine that it can read the .obj file generated by the compiler and follow its instructions for operations.",
    tags: [
      {
        name: "python3",
        color: "blue-text-gradient",
      },
      {
        name: "ply",
        color: "green-text-gradient",
      },
    ],
    image: compiler,
    source_code_link: "https://github.com/JuanMBriones/Obiecti",
  },
  {
    name: "Equilibrium",
    description:
      "A physics simulator that helps students learn concepts like torque allowing them play with a balance and characters. They can reforce concepts with quizzes.",
    tags: [
      {
        name: "swift",
        color: "blue-text-gradient",
      }
    ],
    image: simulator,
    source_code_link: "https://github.com/aroquev00/moviles-proyecto",
  },
];

export { services, technologies, experiences, testimonials, projects };